### ISSUE TITLE
Android 29以下返回失效

### ISSUE THREAD

**Issue by kevinroy-lo** [ssseasonnn/Butterfly#2]
Android Version： Android 9 

ActivityTracker 中使用了onActivityPreCreated，在Android 29以下， 这个方法不会被调用。
Activity栈中记录不到新增的Activity，导致返回失效。

**Comment by ssseasonnn** [comment]
好的，收到反馈

**Comment by ssseasonnn** [comment]
修复了，更新下版本1.2.3试试
